# Generated by Django 5.2.8 on 2025-11-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('drinks', 'Drinks'), ('main', 'Main Dishes'), ('appetizers', 'Appetizers')], max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
