# Generated by Django 5.2.8 on 2025-11-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('main', 'Main Dishes'), ('appetizers', 'Appetizers'), ('sweet', 'Sweet'), ('special', 'Special Dishes')], max_length=50),
        ),
    ]
